# Generated by Django 5.1 on 2024-08-31 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derecho', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_cita', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AGENDADA', 'Agendada'), ('ATENDIDO', 'Atendido')], default='PENDIENTE', max_length=20)),
                ('derecho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiojuridico.asesoramiento')),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiojuridico.cliente')),
            ],
        ),
    ]
