# Generated by Django 5.1 on 2024-08-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiojuridico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='descripcion',
            new_name='motivo_consulta',
        ),
    ]
