# Generated by Django 5.1 on 2024-08-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiojuridico', '0002_rename_descripcion_cita_motivo_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='dni',
            new_name='cliente',
        ),
    ]
