# Generated by Django 5.1 on 2024-08-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiojuridico', '0003_rename_dni_cita_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoramiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
