# Generated by Django 5.1 on 2024-08-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiojuridico', '0004_alter_asesoramiento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
